name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install -y build-essential libboost-all-dev cmake zlib1g-dev libbz2-dev liblzma-dev
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake -DCOMPILE_TESTS=ON ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: Test
      working-directory: build
      run: ctest -j2
